server.port: 0
spring:
  application:
    name: foo-source
  cloud:
    function:
      definition: supplyFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          supplyFoo-out-0: output
      bindings:
        output:
          destination: foo-source
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
server.port: 8080
