server.port: 0
spring:
  application:
    name: bar-sink
  cloud:
    function:
      definition: storeFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          storeFoo-in-0: input
      bindings:
        input:
          destination: foo-result
          group: foo-result-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
server.port: 8080
