apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bar-sink
  labels:
    apps.tanzu.vmware.com/workload-type: worker
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: bar-sink
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "21"
  resources:
    requests:
      memory: 500M
      cpu: 100m
    limits:
      memory: 750M
      cpu: "1.5"
  serviceClaims:
  - name: msgbroker
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: stream-broker
  source:
    git:
      url: https://github.com/trisberg/scdf-tp4k8s
      ref:
        branch: main
    subPath: bar-sink
